name: Update README

            on:
              schedule:
                - cron: '*/30 * * * *'
              workflow_dispatch:
            
            jobs:
              build:
                runs-on: ubuntu-latest
                name: Update this repo's README with recent activity
            
                steps:
                  - uses: actions/checkout@v2
                  - uses: VinitGurjar/github-activity-readme@master
                    env:
                      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
- name: First interaction
  uses: actions/first-interaction@v1.1.1
  with:
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # Comment to post on an individual's first issue
    issue-message: # optional
    # Comment to post on an individual's first pull request
    pr-message: # optional
